config/routes.rb
# coding: utf-8
Shortslide::Application.routes.draw do

  # devise_for :users
  devise_for :users, :path => "", :path_names => {
    :sign_in => 'signin', :sign_out => 'signout', :password => 'password',
    :confirmation => 'verification',
    :unlock => 'unblock'
  }, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # テンプレート
  # resources :templates do
  #   get 'preview'
  # end

  # スライド
  resources :slides do
    resources :pages, :only => [:index]
    resource :controls, :only => [:show, :create]
    get 'lock'
  end
  post 'slides/preview' => 'slides#preview'

  # 画像管理
  resources :images, :only => [:index, :create, :destroy]
  get 'flickr' => 'flickr#index'

  get 'settings/profile' => 'profile#edit'
  patch 'settings/profile' => 'profile#update'

  root "slides#index"

end

app/models/slide.rb
# coding: utf-8
class Slide < ActiveRecord::Base
  belongs_to :user
  validates :title, :presence => true

  def pages
    ret = []
    if content
      content.each_line do |line|
        ret << Page.new(id: ret.length + 1) if line =~ /^## /
        unless line.chomp.empty?
          ret << Page.new(id: "nbsp;") unless ret.last
          ret.last.content << line.chomp 
        end
      end
    end
    ret
  end
end

app/controllers/slides_controller.rb
# coding: utf-8

class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :share, :edit, :update, :destroy, :lock]
  skip_filter :authenticate_user!, :only => [:show, :share, :lock]

  # GET /slides
  def index
    @slides = current_user.slides
  end

  # GET /slides/1
  # GET /slides/1.js
  # GET /slides/1.css
  def show
    respond_to do |format|
      format.html { render layout: 'shower' }
      format.js { render text: @slide.script }
      format.css { render text: @slide.style }
    end
  end

  # GET /slides/1/lock
  def lock
    render layout: 'shower'
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # POST /slides
  def create
    @slide = Slide.new(slide_params)
    @slide.user_id = current_user.id

    respond_to do |format|
      if @slide.save
        format.html { redirect_to slide_pages_url(@slide) }
        format.json { render action: 'show', status: :created, location: @slide }
      else
        format.html { render action: 'new' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /slides/1/edit
  def edit
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to slide_pages_url(@slide), notice: 'Slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url }
      format.json { head :no_content }
    end
  end

  # POST /slides/preview
  def preview
    @slide = Slide.new(slide_params)

    render layout: 'shower'
  end

  private
    def set_slide
      @slide = Slide.find(params[:id] || params[:slide_id])
    end

    def slide_params
      params.require(:slide).permit(:title, :content, :script, :style)
    end

end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_control.html.erb
<script type="text/javascript">
var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>');
var channel = pusher.subscribe('slides_' + <%= @slide.id %>);
channel.bind('next', function () {
  shower.next();
});
channel.bind('previous', function () {
  shower.previous();
});
channel.bind('first', function () {
  shower.first();
});
channel.bind('last', function () {
  shower.last();
});
channel.bind('go', function (data) {
  shower.go(parseInt(data.message, 10)-1);
});
</script>

app/views/slides/_form.html.erb
<%= form_for(@slide, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
  <% if @slide.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@slide.errors.count, "error") %> まだ保存されていません</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-sm-2' %>
    <div class="col-sm-6 <%= error_class(@slide, :title) %>">
      <%= f.text_field :title, :class => "form-control", :placeholder => '識別する名前' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/slides/_page.html.erb
<%= link_to slide_path(slide), :class => 'thumbnail' do %>
  <div style="height: 100px;">
    <%= slide.title %>
  </div>
<% end %>
<% if user_signed_in? %>
  <p>
    <%= link_to '編集', slide_pages_path(slide_id: slide.id), :class => 'btn btn-default' %>
    <%= link_to '削除', slide, method: :delete, data: { confirm: '削除してもよろしいですか？' }, :class => 'btn btn-danger' %>
  </p>
<% end %>

app/views/slides/_pages.html.erb
<h1>スライドの一覧</h1>
<hr>
<% if user_signed_in? %>
  <div class="col-xs-3">
    <%= link_to '新しいスライド', new_slide_path, :class => 'btn btn-primary' %>
  </div>
  <div class="col-xs-9">
    <div class="row">
      <% slides.each do |slide| %>
      <div class="col-xs-3">
        <%= render :partial => 'slides/page', :locals => { :slide => slide } %>
      </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="col-xs-12">
    <div class="row">
      <% slides.each do |slide| %>
      <div class="col-xs-3">
        <%= render :partial => 'slides/page', :locals => { :slide => slide } %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/slides/edit.html.erb
<%= render 'form' %>

app/views/slides/index.html.erb
<%= render :partial => 'slides/pages', :locals => { :slides => @slides } %>

app/views/slides/lock.html.erb
<% @slide.pages.each do |page| %>
  <%= render :partial => 'pages/template', :locals => { :page => page } %>
<% end %>
<%= render 'control' %>
<script type="text/javascript">
$(function () {
  shower.slideLock();
});
</script>

app/views/slides/new.html.erb
<%= render 'form' %>

app/views/slides/show.html.erb
<link href="<%= slide_path(@slide, format: 'css') %>" media="all" rel="stylesheet">
<% @slide.pages.each do |page| %>
  <%= render :partial => 'pages/template', :locals => { :page => page } %>
<% end %>
<%= render 'control' %>
<script src="<%= slide_path(@slide, format: 'js') %>"></script>