config/routes.rb
# coding: utf-8
Shortslide::Application.routes.draw do

  # devise_for :users
  devise_for :users, :path => "", :path_names => {
    :sign_in => 'signin', :sign_out => 'signout', :password => 'password',
    :confirmation => 'verification',
    :unlock => 'unblock'
  }, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # テンプレート
  # resources :templates do
  #   get 'preview'
  # end

  # スライド
  resources :slides do
    resources :pages, :only => [:index]
    resource :controls, :only => [:show, :create]
    get 'lock'
  end
  post 'slides/preview' => 'slides#preview'

  # 画像管理
  resources :images, :only => [:index, :create, :destroy]
  get 'flickr' => 'flickr#index'

  get 'settings/profile' => 'profile#edit'
  patch 'settings/profile' => 'profile#update'

  root "slides#index"

end

app/models/control.rb
class Control
  include ActiveModel::Model
  attr_accessor :slide_id, :command, :message

  def execute
    Pusher['slides_' + slide_id.to_s].trigger(command, to_json)
  end
end

app/models/flickr.rb
# coding: utf-8
class Flickr
  class << self
    # Flickrから写真一覧を取得します
    # _user_id_ :: FlickrのユーザID
    def find_by_user_id(user_id)
      search(user_id: user_id)
    end

    private
      def search(params)
        flickr.photos.search(params).map{|photo| Photo.new(photo)}
      end
  end

  class Photo
    def initialize(photo)
      @photo = photo
    end

    def as_json options = {}
      {url: url("m"), medium: url("b")}
    end

    # _size_ :: m,s,t,z,bのいづれか
    def url(size = "b")
      "http://farm#{farm_id}.staticflickr.com/#{server_id}/#{id}_#{secret}_#{size}.jpg"
    end

    private
      def id
        @photo["id"]
      end

      def farm_id
        @photo["farm"]
      end

      def server_id
        @photo["server"]
      end

      def secret
        @photo["secret"]
      end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  # has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :file,
    :storage => :s3,
    :s3_credentials => S3_CREDENTIALS,
    :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates :file, :attachment_presence => true

  def as_json options = {}
    super :methods => [:url, :medium]
  end

  def url
    file.url
  end

  def medium
    file.url(:medium)
  end
end

app/models/page.rb
class Page
  include ActiveModel::Model
  attr_accessor :id

  def content
    @content ||= []
  end

  def content=(content)
    @content = content
  end

  def html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(content.join("\n"))
  end

  def class_names
    if content.length == 1
      ["shout"]
    elsif content.length == 2 && content[1] =~ /<img /
      ["cover"]
    else
      []
    end
  end
end

app/models/slide.rb
# coding: utf-8
class Slide < ActiveRecord::Base
  belongs_to :user
  validates :title, :presence => true

  def pages
    ret = []
    if content
      content.each_line do |line|
        ret << Page.new(id: ret.length + 1) if line =~ /^## /
        unless line.chomp.empty?
          ret << Page.new(id: "nbsp;") unless ret.last
          ret.last.content << line.chomp 
        end
      end
    end
    ret
  end
end

app/models/template.rb
# coding: utf-8
class Template < ActiveRecord::Base
  validates :name, :presence => true
  validates :content, :presence => true

  # テンプレートのパラメタ一覧を返します。
  # _return_ :: Array
  def params
    content.scan(/{{(.*?)}}/).flatten.map{|lang| lang.strip }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  # attr_accessible :provider, :uid, :name
  attr_accessor :login
  has_many :slides

  class << self
    def find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

    def find_for_facebook_oauth(auth)
      where(auth.slice(:provider, :uid)).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name   # assuming the user model has a name
        user.image_url = auth.info.image # assuming the user model has an image
      end
    end
  end

  def flickrs
    flickr_user_id ? Flickr.find_by_user_id(flickr_user_id) : []
  end
end

app/controllers/flickr_controller.rb
class FlickrController < ApplicationController
  def index
    @flickrs = current_user.flickrs

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @flickrs }
    end
  end
end

app/controllers/images_controller.rb
# coding: utf-8
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :destroy]

  # GET /images
  def index
    @image = Image.new
    @images = Image.all

    respond_to do |format|
      format.html { render action: 'index' }
      format.json { render json: @images }
    end
  end

  def create
    @image = Image.create(image_params)

    redirect_to images_url
  end

  def destroy
    @image.destroy

    redirect_to images_url
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:file)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_slide

  # GET /slides/1/pages
  def index
    @pages = @slide.pages
  end

  # PATCH/PUT /slides/1/pages/1
  # PATCH/PUT /slides/1/pages/1.json
  def update
    respond_to do |format|
      if @slide.update(page_params)
        format.html { redirect_to slide_pages_url(@slide) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_slide
      @slide = Slide.find(params[:slide_id])
    end

    def page_params
      params.require(:slide).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_class(model, name)
    if model.errors[name].any?
      "has-error"
    end
  end
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/helpers/flickr_helper.rb
module FlickrHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shortslide" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "ShortSlide", root_path, :class => 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li><%= link_to "Images", images_path %></li>
            </ul>
            <div class="navbar-form navbar-right">
              <%= link_to settings_profile_path, :class => 'btn icon' do %>
                <img src="/icon/glyphicons_settings_black.png"></img>
              <% end %>
              <%= link_to destroy_user_session_path, :method => :delete, :class => 'btn icon' do %>
                <img src="/icon/glyphicons_exit_black.png"></img>
              <% end %>
            </div>
          <% else %>
            <div class="navbar-form navbar-right">
              <%= link_to "Login", new_user_session_path, :class => "btn btn-default" %>
            </div>
          <% end %>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!--
        <div class="col-xs-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
      -->
      </div><!--/row-->

      <footer>
        <hr />
        <p>&copy; ino-h.com 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/shower.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortslide</title>
  <%= stylesheet_link_tag "shower-print", media: "print" %>
  <%= stylesheet_link_tag "shower-screen", media: "all" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="list">

<%= yield %>

<%= javascript_include_tag 'shower' %>

<%= yield :javascript %>

</body>
</html>

app/views/layouts/slides.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortslide</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= stylesheet_link_tag "shower-print", media: "print" %>
  <%= stylesheet_link_tag "shower-screen", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="list">

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@slide, :html => {:id => 'slide-form', :class => 'form-horizontal', :role => 'form'}) do |f| %>
  <% if @slide.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@slide.errors.count, "error") %> まだ保存されていません</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-sm-2' %>
    <div class="col-sm-10 <%= error_class(@slide, :content) %>">
      <%= f.hidden_field :id %>
      <%= f.text_field :title, :class => "form-control", :placeholder => 'タイトル' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-sm-2' %>
    <div role="tabpanel" class="col-sm-10 <%= error_class(@slide, :content) %>">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#content" aria-controls="content" role="tab" data-toggle="tab">content</a></li>
        <li role="presentation"><a href="#script" aria-controls="script" role="tab" data-toggle="tab">script</a></li>
        <li role="presentation"><a href="#style" aria-controls="style" role="tab" data-toggle="tab">style</a></li>
      </ul>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="content">
          <%= f.text_area :content, :class => "form-control", :rows => 20, :placeholder => 'MARKDOWNで入力してください' %>
        </div>
        <div role="tabpanel" class="tab-pane" id="script">
          <%= f.text_area :script, :class => "form-control", :rows => 20, :placeholder => 'javascriptを入力してください' %>
        </div>
        <div role="tabpanel" class="tab-pane" id="style">
          <%= f.text_area :style, :class => "form-control", :rows => 20, :placeholder => 'stylesheetを入力してください' %>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to '表示', slide_path(@slide), :class => 'btn btn-default', :target => 'preview' %>
      <a data-toggle="modal" href="#myModal" class="btn btn-default">写真選択</a>
    </div>
  </div>
<% end %>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">写真一覧</h4>
      </div>
      <div id="images" class="modal-body row">
      </div>
      <div class="modal-footer">
        <div class="col-xs-12">
          <button id="modal-close" type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script id="image-template" type="text/template">
<div class="col-xs-4">
  <a href="{{ url }}">
    <img class="img-thumbnail" src="{{ medium }}">
  </a>
</div>
</script>

<%= javascript_include_tag "slides", "data-turbolinks-track" => true %>

app/views/pages/_template.html.erb
<section id="<%= page.id %>" class="slide <%= page.class_names.join(" ") %>"><div>
  <%= raw(page.html) %>
</div></section>

app/views/pages/index.html.erb
<%= render 'form' %>

app/views/templates/_form.html.erb
<%= form_for(@template, :html => {:class => "form-horizontal", :role => "form"}) do |f| %>
  <% if @template.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@template.errors.count, "error") %> まだ保存されていません</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-sm-2' %>
    <div class="col-sm-6 <%= error_class(@template, :name) %>">
      <%= f.text_field :name, :class => "form-control", :placeholder => '識別する名前' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-sm-2' %>
    <div class="col-sm-6 <%= error_class(@template, :content) %>">
      <%= f.text_area :content, :class => "form-control", :rows => 10, :placeholder => 'テンプレートの内容' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-4">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/templates/edit.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'HOME', root_path %></li>
  <li><%= link_to '一覧', templates_path %></li>
  <li class="active">テンプレート修正</li>
</ol>

<%= render 'form' %>

<%= link_to 'Show', @template %>

app/views/templates/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'HOME', root_path %></li>
  <li class="active">テンプレート一覧</li>
</ol>

<div class="row">
<% @templates.each_with_index do |template, index| %>
  <div class="col-sm-12 col-md-6">
    <div>
      <h3><%= template.name %></h3>
      <iframe width="100%" height="300px" src="<%= template_preview_path(template) %>?full#1"></iframe>
      <div class="caption">
        <p>
          <%= link_to 'Edit', edit_template_path(template), :class => 'btn btn-default' %>
          <%= link_to 'Destroy', template, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div>
    </div>
  </div>
<% end %>
</div>

<br>

<%= link_to 'テンプレート登録', new_template_path %>

app/views/templates/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'HOME', root_path %></li>
  <li><%= link_to '一覧', templates_path %></li>
  <li class="active">テンプレート登録</li>
</ol>

<%= render 'form' %>

app/views/templates/preview.html.erb
<%= render :partial => 'pages/template', :locals => { :page => @template } %>

app/views/templates/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'HOME', root_path %></li>
  <li><%= link_to '一覧', templates_path %></li>
  <li class="active">テンプレート確認</li>
</ol>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Content:</strong>
  <pre><%= @template.content %></pre>
</p>

<p>
  <strong>Params:</strong>
  <ul>
    <% @template.params.each do |param| %>
    <li><%= param %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_template_path(@template) %>